

consumers:
  - type: kafka
    name: KafkaConsumerTest
    threadNums: 4
    property:
      bootstrapServers: localhost:9092
      groupId: test-consumer-group
      autoCommit: true
      autoCommitIntervalMs: 10000
      sessionTimeoutMs: 30000
      keySerializer: org.apache.kafka.common.serialization.StringDeserializer
      valueSerializer: com.crescent.alert.core.collector.serde.EventDeserializer
      topic: as_jl_event

producers:
  - type: kafka
    regions:
      - default_region
    property:
      bootstrapServers: localhost:9092
      maxBlockMs: 5000
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: com.crescent.alert.core.collector.serde.EventSerializer
      topic: as_jl_alert
      clientId: default-producer

