

consumers:
  - type: kafka
    name: KafkaConsumerTest
    threadNums: 4
    property:
      bootstrap.servers: localhost:9092
      group.id: test-consumer-group
      enable.auto.commit: true
      auto.commit.interval.ms: 10000
      session.timeout.ms: 30000
      auto.offset.reset: latest
      topics: as_jl_event,as_jl_alert

producers:
  - type: kafka
    regions:
      - default_region
    property:
      bootstrap.servers: localhost:9092
      max.block.ms: 5000
      topics: as_jl_alert
      client.id: default-producer

eventWindowType: memory

